### ISSUE TITLE
Do we need a separate JSON for the read to model map?

### ISSUE THREAD

**Issue by cindyeliang** [LRGASP/lrgasp-submissions#14]
There is no separate JSON depicted for the read to model map in the submissions structure diagram. However, there is a "readModelMap" category in the "ftype" section of the JSON template. Would LRGASP like users to submit a separate JSON for the model map in addition to the JSON for the model gtf?

**Comment by fairliereese** [comment]
I think the idea is to have a list of files in the model json that contains the GTF and the read to model map.

**Comment by diekhans** [comment]
There is one json per pair of GTF and read/model map.  It has also been simplified to just used fix file names rather than specifying them in the json.
