### ISSUE TITLE
ID column must be called “ID”, not IDs, nor transcript_id ...

### ISSUE THREAD

**Issue by diekhans** [LRGASP/lrgasp-submissions#20]
from mock submissions

**Comment by FJPardoPalacios** [comment]
Both expression files uploaded by Cindy showed "ids" instead of "ID" for the first column

Drive "path" of one of them:
Long-read RGASP/Submissions/Cindy_submitter_id/pacbio_isoform_usage_tsv/6-gm12878_quantify.tsv

**Comment by diekhans** [comment]
headers are now validated to have specific names
