### ISSUE TITLE
PB adapters 

### ISSUE THREAD

**Issue by Lutri22** [LRGASP/lrgasp-submissions#28]
Hi, 

I would like to run the default Isoseq3 clustering pipeline on some of the PacBio data. I think to get the FLNC.bam file with the clusters I would need to provide the adapter sequences to lima. As far as am aware of it there is no way to do this from the provided fastq files? 
I would be interested if the fasta file containing the PB adapters (PB_adapters.fasta) available somewhere? 

Many Thanks

**Comment by diekhans** [comment]
Hi, will look into this and get back to you.

**Comment by diekhans** [comment]
The vanilla PacBio adapters are as follows:

>primer_5p
AAGCAGTGGTATCAACGCAGAGTACGGGG
>primer_3p
AAGCAGTGGTATCAACGCAGAGTAC


And the CapTrap PacBio adapters are these:

>primer_5p
TCGTCGGCAGCGTC
>primer_3p
GTCTCGTGGGCTCGG

thanks for asking, we will add this to the documentation
