### ISSUE TITLE
add new Sequel II subread BAMs to the RNA-Seq data matrix

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-submissions#30]
There are 3 extra subread BAM files that were released only recently by the ENCODE DCC (accessions ENCFF005VJA, ENCFF783PVA and ENCFF078IYM). All versions (html + tsv) of the data matrix (https://lrgasp.github.io/lrgasp-submissions/docs/rnaseq-data-matrix.html) should be updated accordingly, thanks in advance Mark :-)

**Comment by diekhans** [comment]
fixed; thanks!

**Comment by julienlag** [comment]
thank you Mark!
