### ISSUE TITLE
python virtual environment for submission/validation tools

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-submissions#34]
Maybe it's me, but in https://lrgasp.github.io/lrgasp-submissions/docs/submission-tools.html, the command:

`python3 -m virtualenv lrgasp-env`

didn't work for me.

`python3 -m venv lrgasp-env` did.

**Comment by diekhans** [comment]
virtualenv needs to be installed separately while venv is part of python3.  This is described in:

   https://stackoverflow.com/questions/44091886/whats-the-difference-between-virtualenv-and-m-venv-in-creating-virtual-env/44091914

The doc has been updated to indicated that virtualenv needs to have been installed or that venv can be used as a much slower option.
