### ISSUE TITLE
lrgasp-validate-entry looks for non-gz files

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-submissions#36]
Even though the documentation states that the models and read_model_map files should be gzipped (`models.gtf.gz` and `read_model_map.tsv.gz`, see https://lrgasp.github.io/lrgasp-submissions/docs/submission.html), `lrgasp-validate-entry` looks for non-gzipped versions of those files in the entry directory, and raises an error if the files are gzipped:

`$ lrgasp-validate-entry iso_detect_ref_crg_CapTrap_PacBio`

> `Error: validation of entry 'iso_detect_ref_crg_CapTrap_PacBio' failed: iso_detect_ref_crg_CapTrap_PacBio/entry.json
> caused by: validation of experiment 'ES_CapTrap_PacBio' failed: iso_detect_ref_crg_CapTrap_PacBio/ES_CapTrap_PacBio/experiment.json
> caused by: validation failed on 'iso_detect_ref_crg_CapTrap_PacBio/ES_CapTrap_PacBio/models.gtf' and 'iso_detect_ref_crg_CapTrap_PacBio/ES_CapTrap_PacBio/read_model_map.tsv'
> caused by: Parse of GTF failed: iso_detect_ref_crg_CapTrap_PacBio/ES_CapTrap_PacBio/models.gtf
> caused by: GTF file does not exist: iso_detect_ref_crg_CapTrap_PacBio/ES_CapTrap_PacBio/models.gtf`

Unzipping the files solves the problem.

**Comment by diekhans** [comment]
fixed in 1.3
