### ISSUE TITLE
creating a team in Synapse is mandatory

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-submissions#37]
there is conflicting information about Synapse teams in this repo.
In https://lrgasp.github.io/lrgasp-submissions/docs/synapse.html it says:

> 2. Optionally, the lab can create a Synapse team (e.g. “Darwin LRGASP Team”) to allow multiple users in the lab to upload.

In fact, `team_id` and `team_name` are required JSON attributes when submitting en entry

**Comment by diekhans** [comment]
Documentation has been updated to indicate that team_name can also be user name.

team_id has been dropped, as this can no longer be found in the documentation
