### ISSUE TITLE
conflicting info on simulated data sample identifiers

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-submissions#39]
According to https://lrgasp.github.io/lrgasp-submissions/docs/metadata-identifiers.html#sample-identifiers, there is only one identifier for simulated data (`synthetic`). However, provided validation scripts accept only `mouse_simulation` and `human_simulation` as simulated sample identifiers

**Comment by diekhans** [comment]
documentation was in error and has been updated to match the code.
