### ISSUE TITLE
Comma-separated column names do not match libraries in experiment.json

### ISSUE THREAD

**Issue by andrewprzh** [LRGASP/lrgasp-submissions#44]
Dear Mark,

a small problem regarding R2C2 submission for challenge 2:
as indicated here, column names in expression.tsv should be comma-separated:
https://lrgasp.github.io/lrgasp-submissions/docs/faq.html

But when comma separated libraries are provided in `libraries` section in experiment.json, the validation reports
```
caused by: experiment field 'libraries' is not valid, value is 'ENCFF379KHH,ENCFF694JLN'
caused by: not a valid symbolic identifier 'ENCFF379KHH,ENCFF694JLN'
```

When libraries are listed one by one in experiment.json, validation fails with: 
`caused by: matrix column 'ENCFF379KHH,ENCFF694JLN' is not listed in experiment_md.libraries for 'H1_mix_r2c2_ont'
`

Thanks a lot!
Andrey

**Comment by diekhans** [comment]
this is fixed in 1.8.0 release
