### ISSUE TITLE
Define process for transfering files, recommend tools.

### ISSUE THREAD

**Issue by diekhans** [LRGASP/lrgasp-submissions#6]
this looks promissing https://rclone.org/

**Comment by julienlag** [comment]
agreed. WRT downloads, at least provide direct links for wget/curl

**Comment by julienlag** [comment]
Andrey suggested this tool: https://github.com/odeke-em/drive#drive

**Comment by diekhans** [comment]
There is also: https://rclone.org/

I haven't used it.

I am a bit worried that this quantity of data is beyond what google drive
is design for.

**Comment by julienlag** [comment]
I agree with Mark

**Comment by diekhans** [comment]
using synapse
